package elements;

public enum TrackType {

	NONE, STRAIGHTHORIZONTAL, STRAIGHTVERTICAL,STRAIGHTLEFTUP, STRAIGHTRIGHTUP, LEFTBUFFER, RIGHTBUFFER, UPBUFFER, DOWNBUFFER, 
	LEFTUPBUFFER, RIGHTUPBUFFER, LEFTDOWNBUFFER, RIGHTDOWNBUFFER, LEFTGAP, RIGHTGAP, UPGAP, DOWNGAP, LEFTUPGAP, RIGHTUPGAP, 
	LEFTDOWNGAP, RIGHTDOWNGAP, DIRECTRIGHT, DIRECTLEFT, DIRECTUP, DIRECTDOWN, DIRECTLEFTUP, DIRECTRIGHTUP, DIRECTLEFTDOWN, DIRECTRIGHTDOWN,
	EXITLEFT, EXITRIGHT, EXITUP, EXITDOWN, EXITLEFTUP, EXITRIGHTUP, EXITLEFTDOWN, EXITRIGHTDOWN
}
