package elements;

public enum TrackType {

	NONE, STRAIGHTHORIZONTAL, STRAIGHTVERTICAL, LEFTBUFFER, RIGHTBUFFER, UPBUFFER, DOWNBUFFER, 
	LEFTUPBUFFER, RIGHTUPBUFFER, LEFTDOWNBUFFER, RIGHTDOWNBUFFER, LEFTGAP, RIGHTGAP, UPGAP, DOWNGAP, LEFTUPGAP, RIGHTUPGAP, 
	LEFTDOWNGAP, RIGHTDOWNGAP, DIRECTRIGHT, DIRECTLEFT, DIRECTUP, DIRECTDOWN
}
