	package elements;

public enum TrackType {

	NONE, STRAIGHTHORIZONTAL, STRAIGHTVERTICAL,STRAIGHTLEFTUP, STRAIGHTRIGHTUP, LEFTBUFFER, RIGHTBUFFER, UPBUFFER, DOWNBUFFER, 
	LEFTUPBUFFER, RIGHTUPBUFFER, LEFTDOWNBUFFER, RIGHTDOWNBUFFER, LEFTGAP, RIGHTGAP, UPGAP, DOWNGAP, LEFTUPGAP, RIGHTUPGAP, 
	LEFTDOWNGAP, RIGHTDOWNGAP, DIRECTRIGHT, DIRECTLEFT, DIRECTUP, DIRECTDOWN, DIRECTLEFTUP, DIRECTRIGHTUP, DIRECTLEFTDOWN, DIRECTRIGHTDOWN,
	EXITLEFT, EXITRIGHT, EXITUP, EXITDOWN, EXITLEFTUP, EXITRIGHTUP, EXITLEFTDOWN, EXITRIGHTDOWN, SIGNALLEFT, SIGNALRIGHT, SIGNALUP, SIGNALDOWN,
	SIGNALLEFTUP, SIGNALRIGHTUP, SIGNALLEFTDOWN, SIGNALRIGHTDOWN, TIGHTCURVE1, TIGHTCURVE2, TIGHTCURVE3, TIGHTCURVE4, CURVE1, CURVE2, CURVE3,
	CURVE4, CURVE5, CURVE6, CURVE7, CURVE8, BRIDGE1, BRIDGE2, UNDERPASS1, UNDERPASS2
}
