package application;

public enum TrackType {

	NONE, STRAIGHTHORIZONTAL, STRAIGHTVERTICAL, LEFTBUFFER, RIGHTBUFFER, TOPBUFFER, BOTTOMBUFFER, 
	LEFTUPBUFFER, RIGHTUPBUFFER, LEFTDOWNBUFFER, RIGHTDOWNBUFFER
}
